'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Spots', [
      {
        id: 1,
        userId: 1,
        address: '9300 W Mall Dr',
        city: 'Everett',
        state: 'WA',
        country: 'USA',
        lat: 47.91403,
        lng: -122.21734,
        name: 'Cozy Retreat Close to Clark Park',
        price: 30.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 2,
        userId: 2,
        address: '317 E 9th St',
        city: 'Port Angeles',
        state: 'WA',
        country: 'USA',
        lat: 48.11047,
        lng: -123.43480,
        name: 'Spare Bedroom Nestled under Mt Olympus',
        price: 45.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 3,
        userId: 3,
        address: '903 S Albert St',
        city: 'Port Angeles',
        state: 'WA',
        country: 'USA',
        lat: 48.10811,
        lng: -123.43058,
        name: 'Relax Next to Olympic National Park!',
        price: 40.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 4,
        userId: 4,
        address: '223 W Park Ave',
        city: 'Port Angeles',
        state: 'WA',
        country: 'USA',
        lat: 48.10201,
        lng: -123.44880,
        name: 'Weekend Getaway at Olympic National Park',
        price: 48.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 5,
        userId: 5,
        address: '158 W 27th St',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        lat: 40.74626,
        lng: -73.99258,
        name: 'Walking Distance to Times Square',
        price: 40,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 6,
        userId: 6,
        address: '580 8th Ave',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        lat: 40.75498,
        lng: -73.99104,
        name: 'Experience the Best of NYC',
        price: 50,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 7,
        userId: 7,
        address: '45 E 81st St',
        city: 'New York',
        state: 'NY',
        country: 'USA',
        lat: 40.77767,
        lng: -73.96041,
        name: 'Cozy Bedroom Right Off Museum Mile, Manhattan',
        price: 65,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 8,
        userId: 8,
        address: '1383 Dean St',
        city: 'Brooklyn',
        state: 'NY',
        country: 'USA',
        lat: 40.67681,
        lng: -73.94255,
        name: 'Comfortable Bed with Public Transport to Manhattan',
        price: 30,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 9,
        userId: 9,
        address: '778 23rd Ave',
        city: 'San Francisco',
        state: 'CA',
        country: 'USA',
        lat: 37.77316,
        lng: -122.48174,
        name: 'Clean, Modern Spare Room Right in the Middle of Town',
        price: 45.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 10,
        userId: 10,
        address: '791 La Playa St',
        city: 'San Francisco',
        state: 'CA',
        country: 'USA',
        lat: 37.77357,
        lng: -122.51010,
        name: 'Relax on the Beach!',
        price: 65.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 11,
        userId: 11,
        address: '3603 Wawona St',
        city: 'San Francisco',
        state: 'CA',
        country: 'USA',
        lat: 37.73605,
        lng: -122.50529,
        name: 'Walking Distance Between San Francisco Zoo and Ocean Beach',
        price: 70.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 12,
        userId: 12,
        address: '1342 S Plymouth Ct',
        city: 'Chicago',
        state: 'IL',
        country: 'USA',
        lat: 41.86470,
        lng: -87.62847,
        name: 'Perfect Weekend Getaway in the Big City',
        price: 55.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 13,
        userId: 13,
        address: '1222 S State St',
        city: 'Chicago',
        state: 'IL',
        country: 'USA',
        lat: 41.86688,
        lng: -87.62732,
        name: 'Rustic Farmhouse Spare Room',
        price: 50.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 14,
        userId: 14,
        address: '1220 Comox St',
        city: 'Vancouver',
        state: 'BC',
        country: 'Canada',
        lat: 49.28334,
        lng: -123.13177,
        name: 'Cozy Attic Room in Downtown Vancouver',
        price: 55.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 15,
        userId: 15,
        address: '701 W Georgia St',
        city: 'Vancouver',
        state: 'BC',
        country: 'Canada',
        lat: 49.28472,
        lng: -123.11625,
        name: '5 minutes from Vancouver Art Gallery',
        price: 59.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 16,
        userId: 16,
        address: '814 Richards St',
        city: 'Vancouver',
        state: 'BC',
        country: 'Canada',
        lat: 49.27953,
        lng: -123.11807,
        name: 'Two Twin Beds Available Downtown Vancouver',
        price: 30.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 17,
        userId: 17,
        address: '3 Freeman Rd',
        city: 'Hanover',
        state: 'NH',
        country: 'USA',
        lat: 43.70369,
        lng: -72.27469,
        name: 'Walking Distance to Dartmouth Campus',
        price: 40.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 18,
        userId: 18,
        address: '819 Bourbon St',
        city: 'New Orleans',
        state: 'LA',
        country: 'USA',
        lat: 29.95994,
        lng: -90.06459,
        name: 'Stay in the French Quarter!',
        price: 50.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 19,
        userId: 19,
        address: '300 Royal St',
        city: 'New Orleans',
        state: 'LA',
        country: 'USA',
        lat: 29.95488,
        lng: -90.06079,
        name: 'Farmhouse Chic in the French Quarter',
        price: 55.00,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 20,
        userId: 20,
        address: '913 15th Ave S',
        city: 'Nashville',
        state: 'TN',
        country: 'USA',
        lat: 36.14701,
        lng: -86.79022,
        name: 'Welcome to Music City!',
        price: 40.00,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Spots', null, {});
  }
};
